# Generated by Django 3.0.6 on 2020-05-27 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time1', models.DateTimeField()),
                ('end_time1', models.DateTimeField()),
                ('start_time2', models.DateTimeField()),
                ('end_time2', models.DateTimeField()),
                ('start_time3', models.DateTimeField()),
                ('end_time3', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vikas.User')),
            ],
        ),
    ]
