# Generated by Django 3.0.6 on 2020-05-27 03:52

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vikas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default=''),
            preserve_default=False,
        ),
    ]
