# Generated by Django 3.0.6 on 2020-05-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vikas', '0002_user_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_period',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vikas.User', unique=True),
        ),
    ]
